### ISSUE TITLE
Types sometimes written to file multiple times when referenced from another type multiple times

### ISSUE THREAD

**Issue by rkok** [johngeorgewright/runtyping#68]
Here's an odd one.

Given this input:
```ts
// input.ts
type FooType = string | null; // OR:
// type FooType = string | undefined;
// type FooType = string | number;

// AND

type HorseType = {
    a: FooType,
    b: FooType
} 
// OR:
// interface HorseType {
//     a: FooType,
//     b: FooType
// }
```
```yml
# runtyping.yml
- targetFile: output.ts
  sourceTypes:
    - file: input.ts
      type: HorseType
    - file: input.ts
      type: FooType
```
One would expect:
```ts
// output.ts
export const FooType = Null.Or(String);
export type FooType = Static<typeof FooType>;
export const HorseType = Record({ a: FooType, b: FooType, });
export type HorseType = Static<typeof HorseType>;
```
But instead the output is:
```ts
export const FooType = Null.Or(String);
export type FooType = Static<typeof FooType>;
export const HorseType = Record({ a: FooType, b: FooType, });
export type HorseType = Static<typeof HorseType>;
export const FooType = Null.Or(String);       // <-- TS2451: Cannot redeclare block-scoped variable 'FooType'.
export type FooType = Static<typeof FooType>; // <-- TS2451: Cannot redeclare block-scoped variable 'FooType'.
```

Strangely we _do_ get the expected output when using:
```ts
// input.ts
type FooType = null; // OR:
// type FooType = string;
// type FooType = string | 'some literal';
```

**Comment by johngeorgewright** [comment]
Ah. I must have introduced a big in the last major update.

Do you get the same behaviour when using the following?

```yaml
- targetFile: output.ts
  sourceTypes:
    - file: input.ts
      type: [HorseType, FooType]
```
